<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            ['id' => 1, 'name' =>  'Phin Sữa Tươi Bánh Flan', 'price' => 49000, 'category_id' => 1, 'image' =>  '1704187744_8084.jpg', 'description' =>  'Tỉnh tức thì cùng cà phê Robusta pha phin đậm đà và bánh flan núng nính. Uống là tỉnh ăn là dính xứng đáng là highlight trong ngày của bạn.', 'sale_price' => 0],
            ['id' => 2, 'name' =>  'Trà Xanh Espresso Marble', 'price' => 49000, 'category_id' => 1, 'image' =>  'tra-xanh-espresso-marble.jpg', 'description' =>  'Cho ngày thêm tươi tỉnh êm mượt với Trà Xanh Espresso Marble. Đây là sự mai mối bất ngờ giữa trà xanh Tây Bắc vị mộc và cà phê Arabica Đà Lạt. Muốn ngày thêm chút highlight nhớ tìm đến sự bất ngờ này bạn nhé!', 'sale_price' => 0],
            ['id' => 3, 'name' =>  'Đường Đen Sữa Đá', 'price' => 45000, 'category_id' => 2, 'image' =>  'duong-den-sua-da.webp', 'description' =>  'Nếu chuộng vị cà phê đậm đà bùng nổ và thích vị đường đen ngọt thơm Đường Đen Sữa Đá đích thị là thức uống dành cho bạn. Không chỉ giúp bạn tỉnh táo buổi sáng Đường Đen Sữa Đá còn hấp dẫn đến ngụm cuối cùng bởi thạch cà phê giòn dai nhai cực cuốn. - Khuấy đều trước khi sử dụng\r\n\r\n', 'sale_price' => 0],
            ['id' => 4, 'name' =>  'The Coffee House Sữa Đá', 'price' => 39000, 'category_id' => 2, 'image' =>  'the-coffee-house-sua-da.webp', 'description' =>  'Thức uống giúp tỉnh táo tức thì để bắt đầu ngày mới thật hứng khởi. Không đắng khét như cà phê truyền thống The Coffee House Sữa Đá mang hương vị hài hoà đầy lôi cuốn. Là sự đậm đà của 100% cà phê Arabica Cầu Đất rang vừa tới biến tấu tinh tế với sữa đặc và kem sữa ngọt ngào cực quyến rũ. Càng hấp dẫn hơn với topping thạch 100% cà phê nguyên chất giúp giữ trọn vị ngon đến ngụm cuối cùng.', 'sale_price' => 0],
            ['id' => 5, 'name' =>  'Cà Phê Sữa Đá', 'price' => 29000, 'category_id' => 2, 'image' =>  'ca-phe-sua-da.webp', 'description' =>  'Cà phê Đắk Lắk nguyên chất được pha phin truyền thống kết hợp với sữa đặc tạo nên hương vị đậm đà hài hòa giữa vị ngọt đầu lưỡi và vị đắng thanh thoát nơi hậu vị.\r\n\r\n', 'sale_price' => 0],
            ['id' => 6, 'name' =>  'Cà Phê Sữa Nóng', 'price' => 39000, 'category_id' => 2, 'image' =>  'ca-phe-sua-nong.jpg', 'description' =>  'Cà phê được pha phin truyền thống kết hợp với sữa đặc tạo nên hương vị đậm đà hài hòa giữa vị ngọt đầu lưỡi và vị đắng thanh thoát nơi hậu vị.\r\n\r\n', 'sale_price' => 0],
            ['id' => 7, 'name' =>  'Bạc Sỉu', 'price' => 29000, 'category_id' => 2, 'image' =>  'bac-siu.jpg', 'description' =>  'Bạc sỉu chính là \"Ly sữa trắng kèm một chút cà phê\". Thức uống này rất phù hợp những ai vừa muốn trải nghiệm chút vị đắng của cà phê vừa muốn thưởng thức vị ngọt béo ngậy từ sữa.', 'sale_price' => 0],
            ['id' => 8, 'name' =>  'Bạc Sỉu Nóng', 'price' => 39000, 'category_id' => 2, 'image' =>  'bac-siu-nong.jpg', 'description' =>  'Bạc sỉu chính là \"Ly sữa trắng kèm một chút cà phê\". Thức uống này rất phù hợp những ai vừa muốn trải nghiệm chút vị đắng của cà phê vừa muốn thưởng thức vị ngọt béo ngậy từ sữa.\r\n\r\n', 'sale_price' => 0],
            ['id' => 9, 'name' =>  'Cà Phê Đen Đá', 'price' => 29000, 'category_id' => 2, 'image' =>  'ca-phe-den-da.jpg', 'description' =>  'Không ngọt ngào như Bạc sỉu hay Cà phê sữa Cà phê đen mang trong mình phong vị trầm lắng thi vị hơn. Người ta thường phải ngồi rất lâu mới cảm nhận được hết hương thơm ngào ngạt phảng phất mùi cacao và cái đắng mượt mà trôi tuột xuống vòm họng.', 'sale_price' => 0],
            ['id' => 10, 'name' =>  'Cà Phê Đen Nóng', 'price' => 39000, 'category_id' => 2, 'image' =>  'ca-phe-den-nong.jpg', 'description' =>  'Không ngọt ngào như Bạc sỉu hay Cà phê sữa Cà phê đen mang trong mình phong vị trầm lắng thi vị hơn. Người ta thường phải ngồi rất lâu mới cảm nhận được hết hương thơm ngào ngạt phảng phất mùi cacao và cái đắng mượt mà trôi tuột xuống vòm họng.', 'sale_price' => 0],
            ['id' => 11, 'name' =>  'Cà Phê Sữa Đá Chai Fresh 250ML', 'price' => 75000, 'category_id' => 2, 'image' =>  'ca-phe-sua-da-chai-fresh-250ml.jpg', 'description' =>  'Vẫn là hương vị cà phê sữa đậm đà quen thuộc của The Coffee House nhưng khoác lên mình một chiếc áo mới tiện lợi hơn tiết kiệm hơn phù hợp với bình thường mới giúp bạn tận hưởng một ngày dài trọn vẹn. *Sản phẩm dùng ngon nhất trong ngày. *Sản phẩm mặc định mức đường và không đá.', 'sale_price' => 0],
            ['id' => 12, 'name' =>  'Đường Đen Marble Latte', 'price' => 55000, 'category_id' => 3, 'image' =>  'duong-den-marble-latte.webp', 'description' =>  'Đường Đen Marble Latte êm dịu cực hấp dẫn bởi vị cà phê đắng nhẹ hoà quyện cùng vị đường đen ngọt thơm và sữa tươi béo mịn. Sự kết hợp đầy mới mẻ của cà phê và đường đen cũng tạo nên diện mạo phân tầng đẹp mắt. Đây là lựa chọn đáng thử để bạn khởi đầu ngày mới đầy hứng khởi. - Khuấy đều trước khi sử dụng\r\n\r\n', 'sale_price' => 0],
            ['id' => 13, 'name' =>  'Caramel Macchiato Đá', 'price' => 55000, 'category_id' => 3, 'image' =>  'caramel-macchiato-da.jpg', 'description' =>  'Khuấy đều trước khi sử dụng Caramel Macchiato sẽ mang đến một sự ngạc nhiên thú vị khi vị thơm béo của bọt sữa sữa tươi vị đắng thanh thoát của cà phê Espresso hảo hạng và vị ngọt đậm của sốt caramel được gói gọn trong một tách cà phê.', 'sale_price' => 0],
            ['id' => 14, 'name' =>  'Caramel Macchiato Nóng', 'price' => 55000, 'category_id' => 3, 'image' =>  'caramel-macchiato-nong.jpg', 'description' =>  'Caramel Macchiato sẽ mang đến một sự ngạc nhiên thú vị khi vị thơm béo của bọt sữa sữa tươi vị đắng thanh thoát của cà phê Espresso hảo hạng và vị ngọt đậm của sốt caramel được gói gọn trong một tách cà phê.', 'sale_price' => 0],
            ['id' => 15, 'name' =>  'Latte Đá', 'price' => 55000, 'category_id' => 3, 'image' =>  'latte-da.jpg', 'description' =>  'Một sự kết hợp tinh tế giữa vị đắng cà phê Espresso nguyên chất hòa quyện cùng vị sữa nóng ngọt ngào bên trên là một lớp kem mỏng nhẹ tạo nên một tách cà phê hoàn hảo về hương vị lẫn nhãn quan.', 'sale_price' => 0],
            ['id' => 16, 'name' =>  'Latte Nóng', 'price' => 55000, 'category_id' => 3, 'image' =>  'latte-nong.jpg', 'description' =>  'Một sự kết hợp tinh tế giữa vị đắng cà phê Espresso nguyên chất hòa quyện cùng vị sữa nóng ngọt ngào bên trên là một lớp kem mỏng nhẹ tạo nên một tách cà phê hoàn hảo về hương vị lẫn nhãn quan.', 'sale_price' => 0],
            ['id' => 17, 'name' =>  'Americano Đá', 'price' => 45000, 'category_id' => 3, 'image' =>  'americano-da.jpg', 'description' =>  'Americano được pha chế bằng cách pha thêm nước với tỷ lệ nhất định vào tách cà phê Espresso từ đó mang lại hương vị nhẹ nhàng và giữ trọn được mùi hương cà phê đặc trưng.', 'sale_price' => 0],
            ['id' => 18, 'name' =>  'Americano Nóng', 'price' => 45000, 'category_id' => 3, 'image' =>  'americano-nong.jpg', 'description' =>  'Americano được pha chế bằng cách pha thêm nước với tỷ lệ nhất định vào tách cà phê Espresso từ đó mang lại hương vị nhẹ nhàng và giữ trọn được mùi hương cà phê đặc trưng.\r\n\r\n', 'sale_price' => 0],
            ['id' => 19, 'name' =>  'Cappuccino Đá', 'price' => 55000, 'category_id' => 3, 'image' =>  'cappuccino-da.jpg', 'description' =>  'Capuchino là thức uống hòa quyện giữa hương thơm của sữa vị béo của bọt kem cùng vị đậm đà từ cà phê Espresso. Tất cả tạo nên một hương vị đặc biệt một chút nhẹ nhàng trầm lắng và tinh tế.\r\n\r\n', 'sale_price' => 0],
            ['id' => 20, 'name' =>  'Cappuccino Nóng', 'price' => 55000, 'category_id' => 3, 'image' =>  'cappuccino-nong.jpg', 'description' =>  'Capuchino là thức uống hòa quyện giữa hương thơm của sữa vị béo của bọt kem cùng vị đậm đà từ cà phê Espresso. Tất cả tạo nên một hương vị đặc biệt một chút nhẹ nhàng trầm lắng và tinh tế.', 'sale_price' => 0],
            ['id' => 21, 'name' =>  'Espresso Đá', 'price' => 49000, 'category_id' => 3, 'image' =>  'espresso-da.jpg', 'description' =>  'Một tách Espresso nguyên bản được bắt đầu bởi những hạt Arabica chất lượng phối trộn với tỉ lệ cân đối hạt Robusta cho ra vị ngọt caramel vị chua dịu và sánh đặc.\r\n\r\n', 'sale_price' => 0],
            ['id' => 22, 'name' =>  'Espresso Nóng', 'price' => 45000, 'category_id' => 3, 'image' =>  'espresso-nong.jpg', 'description' =>  'Một tách Espresso nguyên bản được bắt đầu bởi những hạt Arabica chất lượng phối trộn với tỉ lệ cân đối hạt Robusta cho ra vị ngọt caramel vị chua dịu và sánh đặc.\r\n\r\n', 'sale_price' => 0],
            ['id' => 23, 'name' =>  'Cold Brew Phúc Bồn Tử', 'price' => 49000, 'category_id' => 4, 'image' =>  'cold-brew-phuc-bon-tu.jpg', 'description' =>  'Vị chua ngọt của trái phúc bồn tử làm dậy lên hương vị trái cây tự nhiên vốn sẵn có trong hạt cà phê hòa quyện thêm vị đăng đắng ngọt dịu nhẹ nhàng của Cold Brew 100% hạt Arabica Cầu Đất để mang đến một cách thưởng thức cà phê hoàn toàn mới vừa thơm lừng hương cà phê quen thuộc vừa nhẹ nhàng và thanh mát bởi hương trái cây đầy thú vị.\r\n\r\n', 'sale_price' => 0],
            ['id' => 24, 'name' =>  'Cold Brew Sữa Tươi', 'price' => 49000, 'category_id' => 4, 'image' =>  'cold-brew-sua-tuoi.jpg', 'description' =>  'Thanh mát và cân bằng với hương vị cà phê nguyên bản 100% Arabica Cầu Đất cùng sữa tươi thơm béo cho từng ngụm tròn vị hấp dẫn.\r\n\r\n', 'sale_price' => 0],
            ['id' => 25, 'name' =>  'Cold Brew Truyền Thống', 'price' => 45000, 'category_id' => 4, 'image' =>  'cold-brew-truyen-thong.jpg', 'description' =>  'Tại The Coffee House Cold Brew được ủ và phục vụ mỗi ngày từ 100% hạt Arabica Cầu Đất với hương gỗ thông hạt dẻ nốt sô-cô-la đặc trưng thoang thoảng hương khói nhẹ giúp Cold Brew giữ nguyên vị tươi mới.\r\n\r\n', 'sale_price' => 0],
            ['id' => 26, 'name' =>  'Trà Long Nhãn Hạt Sen', 'price' => 49000, 'category_id' => 5, 'image' =>  'tra-long-nhan-hat-sen.jpg', 'description' =>  'Thức uống mang hương vị của nhãn của sen của trà Oolong đầy thanh mát cho tất cả các thành viên trong dịp Tết này. An lành thư thái và đậm đà chính là những gì The Coffee House mong muốn gửi trao đến bạn và gia đình.\r\n\r\n', 'sale_price' => 0],
            ['id' => 27, 'name' =>  'Trà Đào Cam Sả Đá', 'price' => 49000, 'category_id' => 5, 'image' =>  'tra-dao-cam-sa-da.webp', 'description' =>  'Vị thanh ngọt của đào vị chua dịu của Cam Vàng nguyên vỏ vị chát của trà đen tươi được ủ mới mỗi 4 tiếng cùng hương thơm nồng đặc trưng của sả chính là điểm sáng làm nên sức hấp dẫn của thức uống này.\r\n\r\n', 'sale_price' => 0],
            ['id' => 28, 'name' =>  'Trà Đào Cam Sả Nóng', 'price' => 59000, 'category_id' => 5, 'image' =>  'tra-dao-cam-sa-nong.jpg', 'description' =>  'Vị thanh ngọt của đào vị chua dịu của Cam Vàng nguyên vỏ vị chát của trà đen tươi được ủ mới mỗi 4 tiếng cùng hương thơm nồng đặc trưng của sả chính là điểm sáng làm nên sức hấp dẫn của thức uống này.\r\n\r\n', 'sale_price' => 0],
            ['id' => 29, 'name' =>  'Trà Đào Cam Sả Chai Fresh 500ML', 'price' => 105000, 'category_id' => 5, 'image' =>  'tra-dao-cam-sa-chai-fresh-500ml.jpg', 'description' =>  'Với phiên bản chai fresh 500ml thức uống \"best seller\" đỉnh cao mang một diện mạo tươi mới tiện lợi phù hợp với bình thường mới và vẫn giữ nguyên vị thanh ngọt của đào vị chua dịu của cam vàng nguyên vỏ và vị trà đen thơm lừng ly Trà đào cam sả nguyên bản. *Sản phẩm dùng ngon nhất trong ngày. *Sản phẩm mặc định mức đường và không đá.\r\n\r\n', 'sale_price' => 0],
            ['id' => 30, 'name' =>  'Trà Hạt Sen Nóng', 'price' => 49000, 'category_id' => 5, 'image' =>  'tra-hat-sen-nong.webp', 'description' =>  'Nền trà oolong hảo hạng kết hợp cùng hạt sen tươi bùi bùi thơm ngon. Trà hạt sen là thức uống thanh mát nhẹ nhàng phù hợp cho cả buổi sáng và chiều tối.\r\n\r\n', 'sale_price' => 0],
            ['id' => 31, 'name' =>  'Trà Hạt Sen Đá', 'price' => 39000, 'category_id' => 5, 'image' =>  'tra-hat-sen-da.jpg', 'description' =>  'Nền trà oolong hảo hạng kết hợp cùng hạt sen tươi bùi bùi và lớp foam cheese béo ngậy. Trà hạt sen là thức uống thanh mát nhẹ nhàng phù hợp cho cả buổi sáng và chiều tối.\r\n\r\n', 'sale_price' => 0],
            ['id' => 38, 'name' =>  'Trà Đen Macchiato', 'price' => 55000, 'category_id' => 6, 'image' =>  'tra-den-macchiato.jpg', 'description' =>  'Trà đen được ủ mới mỗi ngày giữ nguyên được vị chát mạnh mẽ đặc trưng của lá trà phủ bên trên là lớp Macchiato \"homemade\" bồng bềnh quyến rũ vị phô mai mặn mặn mà béo béo.\r\n\r\n', 'sale_price' => 0],
            ['id' => 39, 'name' =>  'Hồng Trà Sữa Trân Châu', 'price' => 55000, 'category_id' => 6, 'image' =>  'hong-tra-sua-tran-chau.webp', 'description' =>  'Thêm chút ngọt ngào cho ngày mới với hồng trà nguyên lá sữa thơm ngậy được cân chỉnh với tỉ lệ hoàn hảo cùng trân châu trắng dai giòn có sẵn để bạn tận hưởng từng ngụm trà sữa ngọt ngào thơm ngậy thiệt đã.\r\n\r\n', 'sale_price' => 0],
            ['id' => 40, 'name' =>  'Hồng Trà Sữa Nóng', 'price' => 55000, 'category_id' => 6, 'image' =>  'hong-tra-sua-nong.jpg', 'description' =>  'Từng ngụm trà chuẩn gu ấm áp đậm đà beo béo bởi lớp sữa tươi chân ái hoà quyện. Trà đen nguyên lá âm ấm dịu nhẹ quyện cùng lớp sữa thơm béo khó lẫn - hương vị ấm áp chuẩn gu trà cho từng ngụm nhẹ nhàng ngọt dịu lưu luyến mãi nơi cuống họng.\r\n\r\n', 'sale_price' => 0],
            ['id' => 41, 'name' =>  'Trà sữa Oolong Nướng Trân Châu', 'price' => 55000, 'category_id' => 6, 'image' =>  'tra-sua-oolong-nuong-tran-chau.webp', 'description' =>  'Hương vị chân ái đúng gu đậm đà với trà oolong được “sao” (nướng) lâu hơn cho hương vị đậm đà, hòa quyện với sữa thơm béo mang đến cảm giác mát lạnh, lưu luyến vị trà sữa đậm đà nơi vòm họng.\r\n\r\n', 'sale_price' => 0],
            ['id' => 42, 'name' =>  'Trà sữa Oolong Nướng (Nóng)', 'price' => 55000, 'category_id' => 6, 'image' => 'tra-sua-oolong-nuong-nong.jpg', 'description' => 'Đậm đà chuẩn gu và ấm nóng - bởi lớp trà oolong nướng đậm vị hoà cùng lớp sữa thơm béo. Hương vị chân ái đúng gu đậm đà - trà oolong được \"sao\" (nướng) lâu hơn cho vị đậm đà, hoà quyện với sữa thơm ngậy. Cho từng ngụm ấm áp, lưu luyến vị trà sữa đậm đà mãi nơi cuống họng.\r\n\r\n', 'sale_price' => 0],
            ['id' => 43, 'name' =>  'Trà Sữa Mắc Ca Trân Châu', 'price' => 55000, 'category_id' => 6, 'image' =>  'tra-sua-mac-ca-tran-chau.webp', 'description' =>  'Mỗi ngày với The Coffee House sẽ là điều tươi mới hơn với sữa hạt mắc ca thơm ngon bổ dưỡng quyện cùng nền trà oolong cho vị cân bằng ngọt dịu đi kèm cùng Trân châu trắng giòn dai mang lại cảm giác “đã” trong từng ngụm trà sữa.\r\n\r\n', 'sale_price' => 0],
            ['id' => 44, 'name' =>  'Trà Sữa Oolong Nướng Trân Châu Chai Fresh 500ML', 'price' => 95000, 'category_id' => 6, 'image' =>  'tra-sua-oolong-nuong-tran-chau-chai-fresh-500ml.jpg', 'description' =>  'Phiên bản chai fresh 500ml mới The Coffee House tin rằng với diện mạo mới: tiện lợi và phù hợp với bình thường mới này các tín đồ trà sữa sẽ được thưởng thức hương vị đậm đà hòa quyện với sữa thơm béo mang đến cảm giác mát lạnh ở bất cứ nơi đâu. *Sản phẩm dùng ngon nhất trong ngày. *Sản phẩm mặc định mức đường và không đá.\r\n\r\n', 'sale_price' => 0],
            ['id' => 45, 'name' =>  'CloudTea Trà Xanh Tây Bắc', 'price' => 69000, 'category_id' => 7, 'image' =>  'cloudtea-tra-xanh-tay-bac.webp', 'description' =>  'Không thể rời môi với Mochi Kem Matcha dẻo mịn núng nính. Trà Xanh Tây Bắc vị mộc hoà quyện sữa tươi foam phô mai beo béo và vụn bánh quy giòn tan là lựa chọn đậm không khí lễ hội.\r\n\r\n', 'sale_price' => 0],
            ['id' => 46, 'name' =>  'CloudTea Oolong Berry', 'price' => 69000, 'category_id' => 7, 'image' =>  'cloudtea-oolong-berry.webp', 'description' =>  'Cắn một cái chua chua ngọt ngọt ngon đến từng tế bào với chiếc Mochi Kem Phúc Bồn Tử! Hút một ngụm mê luôn Trà Oolong Sữa dịu êm quyện vị dâu cùng lớp foam phô mai phủ vụn bánh quy phô mai mằn mặn.\r\n\r\n', 'sale_price' => 0],
            ['id' => 47, 'name' =>  'CloudTea Oolong Nướng Kem Dừa', 'price' => 55000, 'category_id' => 7, 'image' =>  'cloudtea-oolong-nuong-kem-dua.jpg', 'description' =>  'Vừa chạm môi là mê mẩn ngay lớp kem dừa beo béo kèm vụn bánh quy phô mai giòn tan trong miệng. Đặc biệt trà Oolong nướng đậm đà hòa cùng sữa dừa ngọt dịu. Hương vị thêm bùng nổ nhờ có thạch Oolong nướng nguyên chất giòn dai.\r\n\r\n', 'sale_price' => 0],
            ['id' => 48, 'name' =>  'CloudTea Oolong Nướng Kem Cheese', 'price' => 55000, 'category_id' => 7, 'image' =>  'cloudtea-oolong-nuong-kem-cheese.jpg', 'description' =>  'Hội mê cheese sao có thể bỏ lỡ chiếc trà sữa siêu mlem này. Món đậm vị Oolong nướng - nền trà được yêu thích nhất hiện nay quyện thêm kem sữa thơm béo. Đặc biệt chinh phục ngay fan ghiền cheese bởi lớp foam phô mai mềm tan mằn mặn. Càng ngon cực với thạch Oolong nướng nguyên chất giòn dai nhai siêu thích.\r\n\r\n', 'sale_price' => 0],
            ['id' => 49, 'name' =>  'CloudTea Oolong Nướng Kem Dừa Đá Xay', 'price' => 55000, 'category_id' => 7, 'image' =>  'cloudtea-oolong-nuong-kem-dua-da-xay.webp', 'description' =>  'Trà sữa đá xay - phiên bản nâng cấp đầy mới lạ của trà sữa truyền thống lần đầu xuất hiện tại Nhà. Ngon khó cưỡng với lớp kem dừa béo ngậy nhưng không ngấy thêm vụn bánh quy phô mai giòn tan vui miệng. Trà Oolong nướng rõ hương đậm vị quyện với sữa dừa beo béo được xay mịn cùng đá mát rượi trong tích tắc. Đặc biệt thạch Oolong nướng nguyên chất giúp giữ trọn vị đậm đà của trà sữa đến giọt cuối cùng.\r\n\r\n', 'sale_price' => 0],
            ['id' => 50, 'name' =>  'CloudFee Hạnh Nhân Nướng', 'price' => 49000, 'category_id' => 8, 'image' =>  'cloudfee-hanh-nhan-nuong.webp', 'description' =>  'Vị đắng nhẹ từ cà phê phin truyền thống kết hợp Espresso Ý lẫn chút ngọt ngào của kem sữa và lớp foam trứng cacao nhấn thêm hạnh nhân nướng thơm bùi kèm topping thạch cà phê dai giòn mê ly. Tất cả cùng quyện hoà trong một thức uống làm vị giác \"thức giấc\" thơm ngon hết nấc.\r\n\r\n', 'sale_price' => 0],
            ['id' => 51, 'name' =>  'CloudFee Caramel', 'price' => 49000, 'category_id' => 8, 'image' =>  'cloudfee-caramel.webp', 'description' =>  'Ngon khó cưỡng bởi xíu đắng nhẹ từ cà phê phin truyền thống pha trộn với Espresso lừng danh nước Ý quyện vị kem sữa và caramel ngọt ngọt thêm lớp foam trứng cacao bồng bềnh béo mịn kèm topping thạch cà phê dai giòn nhai cực cuốn. Một thức uống \"điểm mười\" cho cả ngày tươi không cần tưới.\r\n\r\n', 'sale_price' => 0],
            ['id' => 52, 'name' =>  'CloudFee Hà Nội', 'price' => 49000, 'category_id' => 8, 'image' =>  'cloudfee-ha-noi.jpg', 'description' =>  'Khiến bạn mê mẩn ngay ngụm đầu tiên bởi vị đắng nhẹ của cà phê phin truyền thống kết hợp Espresso Ý quyện hòa cùng chút ngọt ngào của kem sữa và thơm béo từ foam trứng cacao. Nhấp một ngụm rồi nhai cùng thạch cà phê dai dai giòn giòn đúng chuẩn \"ngon quên lối về\". CloudFee Classic là món đậm vị cà phê nhất trong bộ sưu tập nhưng không quá đắng ngậy nhưng không hề ngấy.\r\n\r\n', 'sale_price' => 0],
            ['id' => 53, 'name' =>  'CloudTea Oolong Berry', 'price' => 69000, 'category_id' => 9, 'image' =>  'cloudtea-oolong-berry.webp', 'description' =>  'Cắn một cái chua chua ngọt ngọt ngon đến từng tế bào với chiếc Mochi Kem Phúc Bồn Tử! Hút một ngụm mê luôn Trà Oolong Sữa dịu êm quyện vị dâu cùng lớp foam phô mai phủ vụn bánh quy phô mai mằn mặn.\r\n\r\n', 'sale_price' => 0],
            ['id' => 54, 'name' =>  'CloudTea Trà Xanh Tây Bắc', 'price' => 69000, 'category_id' => 9, 'image' =>  'cloudtea-tra-xanh-tay-bac.webp', 'description' =>  'Không thể rời môi với Mochi Kem Matcha dẻo mịn núng nính. Trà Xanh Tây Bắc vị mộc hoà quyện sữa tươi foam phô mai beo béo và vụn bánh quy giòn tan là lựa chọn đậm không khí lễ hội.\r\n\r\n', 'sale_price' => 0],
            ['id' => 55, 'name' =>  'Hi Tea Đào Kombucha', 'price' => 59000, 'category_id' => 10, 'image' =>  'hi-tea-dao-kombucha.webp', 'description' =>  'Trà hoa Hibiscus 0% caffeine chua nhẹ kết hợp cùng trà lên men Kombucha hoàn toàn tự nhiên và Đào thanh mát tạo nên Hi-Tea Đào Kombucha chua ngọt cực cuốn. Đặc biệt Kombucha Detox giàu axit hữu cơ Đào nhiều chất xơ giúp thanh lọc cơ thể và hỗ trợ giảm cân hiệu quả. Lưu ý: Khuấy đều trước khi dùng\r\n\r\n', 'sale_price' => 0],
            ['id' => 56, 'name' =>  'Hi Tea Yuzu Kombucha', 'price' => 59000, 'category_id' => 10, 'image' =>  'hi-tea-yuzu-kombucha.jpg', 'description' =>  'Trà hoa Hibiscus 0% caffeine thanh mát hòa quyện cùng trà lên men Kombucha 100% tự nhiên và mứt Yuzu Marmalade (quýt Nhật) mang đến hương vị chua chua lạ miệng. Đặc biệt, Hi-Tea Yuzu Kombucha cực hợp cho team thích detox, muốn sáng da nhờ Kombucha Detox nhiều chất chống oxy hoá cùng Yuzu giàu vitamin C. Lưu ý: Khuấy đều trước khi dùng\r\n\r\n', 'sale_price' => 0],
            ['id' => 57, 'name' =>  'Hi Tea Phúc Bồn Tử Mandarin', 'price' => 49000, 'category_id' => 10, 'image' =>  'hi-tea-phuc-bon-tu-mandarin.webp', 'description' =>  'Nền trà Hibiscus thanh mát quyện vị chua chua ngọt ngọt của phúc bồn tử 100% tự nhiên cùng quýt mọng nước mang đến cảm giác sảng khoái tức thì.\r\n\r\n', 'sale_price' => 0],
            ['id' => 58, 'name' =>  'Hi Tea Yuzu Trân Châu', 'price' => 49000, 'category_id' => 10, 'image' =>  'hi-tea-yuzu-tran-chau.png', 'description' =>  'Không chỉ nổi bật với sắc đỏ đặc trưng từ trà hoa Hibiscus Hi-Tea Yuzu còn gây ấn tượng với topping Yuzu (quýt Nhật) lạ miệng, kết hợp cùng trân châu trắng dai giòn sần sật, nhai vui vui.\r\n\r\n', 'sale_price' => 0],
            ['id' => 59, 'name' =>  'Hi Tea Vải', 'price' => 49000, 'category_id' => 10, 'image' =>  'hi-tea-vai.png', 'description' =>  'Chút ngọt ngào của Vải mix cùng vị chua thanh tao từ trà hoa Hibiscus mang đến cho bạn thức uống đúng chuẩn vừa ngon vừa healthy.\r\n\r\n', 'sale_price' => 0],
            ['id' => 60, 'name' =>  'Hi Tea Đào', 'price' => 49000, 'category_id' => 10, 'image' =>  'hi-tea-dao.jpg', 'description' =>  'Sự kết hợp ăn ý giữa Đào cùng trà hoa Hibiscus tạo nên tổng thể hài hoà dễ gây “thương nhớ” cho team thích món thanh mát có vị chua nhẹ.\r\n\r\n', 'sale_price' => 0],
            ['id' => 61, 'name' =>  'Hi Tea Đá Tuyết Yuzu Vải', 'price' => 59000, 'category_id' => 11, 'image' =>  'hi-tea-da-tuyet-yuzu-vai.webp', 'description' =>  'Vị trà hoa Hibiscus chua chua kết hợp cùng đá tuyết Yuzu mát lạnh tái tê thêm miếng vải căng mọng ngọt ngào sẽ khiến bạn thích thú ngay từ lần thử đầu tiên.\r\n\r\n', 'sale_price' => 0],
            ['id' => 62, 'name' =>  'Trà Xanh Latte', 'price' => 45000, 'category_id' => 12, 'image' =>  'tra-xanh-latte.webp', 'description' =>  'Không cần đến Tây Bắc mới cảm nhận được sự trong trẻo của núi rừng khi Trà Xanh Latte từ Nhà được chắt lọc từ những búp trà xanh mướt ủ mình trong sương sớm. Trà xanh Tây Bắc vị thanh chát nhẹ hoà cùng sữa tươi nguyên kem ngọt béo tạo nên hương vị dễ uống dễ yêu. Đây là thức uống healthy giúp bạn tỉnh táo một cách êm mượt xoa dịu những căng thẳng.\r\n\r\n', 'sale_price' => 0],
            ['id' => 63, 'name' =>  'Trà Xanh Latte (Nóng)', 'price' => 45000, 'category_id' => 12, 'image' => 'tra-xanh-latte-nong.webp', 'description' => 'Trà Xanh Latte (Nóng) là phiên bản rõ vị trà nhất. Nhấp một ngụm, bạn chạm ngay vị trà xanh Tây Bắc chát nhẹ hoà cùng sữa nguyên kem thơm béo, đọng lại hậu vị ngọt ngào, êm dịu. Không chỉ là thức uống tốt cho sức khoẻ, Trà Xanh Latte (Nóng) còn là cái ôm ấm áp của đồng bào Tây Bắc gửi cho người miền xuôi.\r\n\r\n', 'sale_price' => 0],
            ['id' => 64, 'name' =>  'Trà Xanh Đường Đen', 'price' => 55000, 'category_id' => 12, 'image' =>  'tra-xanh-duong-den.jpg', 'description' =>  'Trà Xanh Đường Đen với hiệu ứng phân tầng đẹp mắt như phác hoạ núi đồi Tây Bắc bảng lảng trong sương mây thấp thoáng những nương chè xanh ngát. Từng ngụm là sự hài hoà từ trà xanh đậm đà đường đen ngọt ngào sữa tươi thơm béo. Khuấy đều trước khi dùng để thưởng thức đúng vị\r\n\r\n', 'sale_price' => 0],
            ['id' => 65, 'name' =>  'Frosty Trà Xanh', 'price' => 59000, 'category_id' => 12, 'image' =>  'frosty-tra-xanh.webp', 'description' =>  'Đá Xay Frosty Trà Xanh như lời mời mộc mạc ghé thăm Tây Bắc vào những ngày tiết trời se lạnh núi đèo mây phủ. Vị chát dịu ngọt thanh của trà xanh Tây Bắc kết hợp đá xay sánh mịn whipping cream bồng bềnh và bột trà xanh trên cùng thêm đậm vị. Đây không chỉ là thức uống mát lạnh bật mood mà còn tốt cho sức khoẻ nhờ giàu vitamin và các chất chống oxy hoá.\r\n\r\n', 'sale_price' => 0],
            ['id' => 66, 'name' =>  'Chocolate Đá', 'price' => 55000, 'category_id' => 13, 'image' =>  'chocolate-da.jpg', 'description' =>  'Bột chocolate nguyên chất hoà cùng sữa tươi béo ngậy ấm nóng. Vị ngọt tự nhiên không gắt cổ để lại một chút đắng nhẹ cay cay trên đầu lưỡi.\r\n\r\n', 'sale_price' => 0],
            ['id' => 67, 'name' =>  'Frosty Phin Gato', 'price' => 55000, 'category_id' => 14, 'image' =>  'frosty-phin-gato.png', 'description' =>  'Đá Xay Frosty Phin-Gato là lựa chọn không thể bỏ lỡ cho tín đồ cà phê. Cà phê nguyên chất pha phin truyền thống thơm đậm đà đắng mượt mà quyện cùng kem sữa béo ngậy và đá xay mát lạnh. Nhân đôi vị cà phê nhờ có thêm thạch cà phê đậm đà giòn dai. Thức uống khơi ngay sự tỉnh táo tức thì. Lưu ý: Khuấy đều phần đá xay trước khi dùng\r\n\r\n', 'sale_price' => 0],
            ['id' => 68, 'name' =>  'Frosty Cà Phê Đường Đen', 'price' => 59000, 'category_id' => 14, 'image' =>  'frosty-ca-phe-duong-den.png', 'description' =>  'Đá Xay Frosty Cà Phê Đường Đen mát lạnh sảng khoái ngay từ ngụm đầu tiên nhờ sự kết hợp vượt chuẩn vị quen giữa Espresso đậm đà và Đường Đen ngọt thơm. Đặc biệt whipping cream beo béo cùng thạch cà phê giòn dai đậm vị nhân đôi sự hấp dẫn khơi bừng sự hứng khởi trong tích tắc.\r\n\r\n', 'sale_price' => 0],
            ['id' => 69, 'name' =>  'Frosty Caramel Arabica', 'price' => 59000, 'category_id' => 14, 'image' =>  'frosty-caramel-arabica.png', 'description' =>  'Caramel ngọt thơm quyện cùng cà phê Arabica Cầu Đất đượm hương gỗ thông hạt dẻ và nốt sô cô la đặc trưng tạo nên Đá Xay Frosty Caramel Arabica độc đáo chỉ có tại Nhà. Cực cuốn với lớp whipping cream béo mịn thêm thạch cà phê giòn ngon bắt miệng.\r\n\r\n', 'sale_price' => 0],
            ['id' => 70, 'name' =>  'Frosty Bánh Kem Dâu', 'price' => 59000, 'category_id' => 14, 'image' =>  'frosty-banh-kem-dau.png', 'description' =>  'Bồng bềnh như một đám mây Đá Xay Frosty Bánh Kem Dâu vừa ngon mắt vừa chiều vị giác bằng sự ngọt ngào. Bắt đầu bằng cái chạm môi với lớp kem whipping cream cảm nhận ngay vị beo béo lẫn sốt dâu thơm lừng. Sau đó hút một ngụm là cuốn khó cưỡng bởi đá xay mát lạnh quyện cùng sốt dâu ngọt dịu. Lưu ý: Khuấy đều phần đá xay trước khi dùng\r\n\r\n', 'sale_price' => 0],
            ['id' => 71, 'name' =>  'Frosty Choco Chip', 'price' => 59000, 'category_id' => 14, 'image' =>  'frosty-choco-chip.webp', 'description' =>  'Đá Xay Frosty Choco Chip thử là đã! Lớp whipping cream bồng bềnh beo béo lại có thêm bột sô cô la và sô cô la chip trên cùng. Gấp đôi vị ngon với sô cô la thật xay với đá sánh mịn đậm đà đến tận ngụm cuối cùng.\r\n\r\n', 'sale_price' => 0],
            ['id' => 72, 'name' =>  'Bánh Mì Gậy Gà Kim Quất', 'price' => 25000, 'category_id' => 15, 'image' =>  'banh-mi-gay-ga-kim-quat.webp', 'description' =>  'Phiên bản nâng cấp với trọng lượng tăng 80% so với bánh mì que thông thường đem đến cho bạn bữa ăn nhanh gọn mà vẫn đầy đủ dinh dưỡng. Cắn một miếng là mê mẩn bởi vỏ bánh nướng giòn rụm nhân đậm vị với từng miếng thịt gà mềm ướp sốt kim quất chua ngọt thơm nức đặc trưng. Càng \"đúng bài\" hơn khi thưởng thức kèm Cà phê đượm vị hoặc trà Hi-Tea thanh mát.\r\n\r\n', 'sale_price' => 0],
            ['id' => 73, 'name' =>  'Bánh Mì Gậy Cá Ngừ Mayo', 'price' => 25000, 'category_id' => 15, 'image' =>  'banh-mi-gay-ca-ngu-mayo.jpg', 'description' =>  'Trọng lượng tăng 70% so với bánh mì que thông thường thêm nhiều dinh dưỡng thích hợp cho cả bữa ăn nhẹ lẫn ăn no. Ngon hết chỗ chê từ vỏ bánh nướng nóng giòn cá ngừ đậm đà quyện lẫn sốt mayo thơm béo đến từng hạt bắp ngọt bùi hấp dẫn. Nhâm nhi bánh cùng ly Cà phê thơm nồng hay Hi-Tea tươi mát thì đúng chuẩn \"điểm mười\".\r\n\r\n', 'sale_price' => 0],
            ['id' => 74, 'name' =>  'Bánh Mì Que Pate', 'price' => 15000, 'category_id' => 15, 'image' =>  'banh-mi-que-pate.png', 'description' =>  'Vỏ bánh mì giòn tan kết hợp với lớp nhân pate béo béo đậm đà sẽ là lựa chọn lý tưởng nhẹ nhàng để lấp đầy chiếc bụng đói  cho 1 bữa sáng - trưa - chiều - tối của bạn thêm phần thú vị.\r\n\r\n', 'sale_price' => 0],
            ['id' => 75, 'name' =>  'Bánh Mì Que Pate Cay', 'price' => 15000, 'category_id' => 15, 'image' =>  'banh-mi-que-pate-cay.jpg', 'description' =>  'Vỏ bánh mì giòn tan kết hợp với lớp nhân pate béo béo đậm đà và 1 chút cay cay sẽ là lựa chọn lý tưởng nhẹ nhàng để lấp đầy chiếc bụng đói  cho 1 bữa sáng - trưa - chiều - tối của bạn thêm phần thú vị.\r\n\r\n', 'sale_price' => 0],
            ['id' => 76, 'name' =>  'Bánh Mì VN Thịt Nguội', 'price' => 39000, 'category_id' => 15, 'image' =>  'banh-mi-vn-thit-nguoi.jpg', 'description' =>  'Gói gọn trong ổ bánh mì Việt Nam là từng lớp chả từng lớp jambon hòa quyện cùng bơ và pate thơm lừng thêm dưa rau cho bữa sáng đầy năng lượng. *Phần bánh sẽ ngon và đậm đà nhất khi kèm pate. Để đảm bảo hương vị được trọn vẹn Nhà mong bạn thông cảm vì không thể thay đổi định lượng pate.\r\n\r\n', 'sale_price' => 0],
            ['id' => 77, 'name' =>  'Croissant trứng muối', 'price' => 39000, 'category_id' => 15, 'image' =>  'croissant-trung-muoi.jpg', 'description' =>  'Croissant trứng muối thơm lừng bên ngoài vỏ bánh giòn hấp dẫn bên trong trứng muối vị ngon khó cưỡng.\r\n\r\n', 'sale_price' => 0],
            ['id' => 78, 'name' =>  'Chà Bông Phô Mai', 'price' => 39000, 'category_id' => 15, 'image' =>  'cha-bong-pho-mai.png', 'description' =>  'Chiếc bánh với lớp phô mai vàng sánh mịn bên trong được bọc ngoài lớp vỏ xốp mềm thơm lừng. Thêm lớp chà bông mằn mặn hấp dẫn bên trên.\r\n\r\n', 'sale_price' => 0],
            ['id' => 79, 'name' =>  'Mochi Kem Phúc Bồn Tử', 'price' => 19000, 'category_id' => 16, 'image' =>  'mochi-kem-phuc-bon-tu.jpg', 'description' =>  'Bao bọc bởi lớp vỏ Mochi dẻo thơm bên trong là lớp kem lạnh cùng nhân phúc bồn tử ngọt ngào. Gọi 1 chiếc Mochi cho ngày thật tươi mát. Sản phẩm phải bảo quán mát và dùng ngon nhất trong 2h sau khi nhận hàng.\r\n\r\n', 'sale_price' => 0],
            ['id' => 80, 'name' =>  'Mochi Kem Việt Quất', 'price' => 19000, 'category_id' => 16, 'image' =>  'mochi-kem-viet-quat.jpg', 'description' =>  'Bao bọc bởi lớp vỏ Mochi dẻo thơm bên trong là lớp kem lạnh cùng nhân việt quất đặc trưng thơm thơm ngọt dịu. Gọi 1 chiếc Mochi cho ngày thật tươi mát. Sản phẩm phải bảo quán mát và dùng ngon nhất trong 2h sau khi nhận hàng.\r\n\r\n', 'sale_price' => 0],
            ['id' => 81, 'name' =>  'Mochi Kem Dừa Dứa', 'price' => 19000, 'category_id' => 16, 'image' =>  'mochi-kem-dua-dua.jpg', 'description' =>  'Bao bọc bởi lớp vỏ Mochi dẻo thơm bên trong là lớp kem lạnh cùng nhân dừa dứa thơm lừng lạ miệng. Gọi 1 chiếc Mochi cho ngày thật tươi mát. Sản phẩm phải bảo quán mát và dùng ngon nhất trong 2h sau khi nhận hàng.\r\n\r\n', 'sale_price' => 0],
            ['id' => 82, 'name' =>  'Mochi Kem Chocolate', 'price' => 19000, 'category_id' => 16, 'image' =>  'mochi-kem-chocolate.jpg', 'description' =>  'Bao bọc bởi lớp vỏ Mochi dẻo thơm bên trong là lớp kem lạnh cùng nhân chocolate độc đáo. Gọi 1 chiếc Mochi cho ngày thật tươi mát. Sản phẩm phải bảo quán mát và dùng ngon nhất trong 2h sau khi nhận hàng.\r\n\r\n', 'sale_price' => 0],
            ['id' => 83, 'name' =>  'Mochi Kem Matcha', 'price' => 19000, 'category_id' => 16, 'image' =>  'mochi-kem-matcha.jpg', 'description' =>  'Bao bọc bởi lớp vỏ Mochi dẻo thơm bên trong là lớp kem lạnh cùng nhân trà xanh đậm vị. Gọi 1 chiếc Mochi cho ngày thật tươi mát. Sản phẩm phải bảo quán mát và dùng ngon nhất trong 2h sau khi nhận hàng.\r\n\r\n', 'sale_price' => 0],
            ['id' => 84, 'name' =>  'Mochi Kem Xoài', 'price' => 19000, 'category_id' => 16, 'image' =>  'mochi-kem-xoai.jpg', 'description' =>  'Bao bọc bởi lớp vỏ Mochi dẻo thơm bên trong là lớp kem lạnh cùng nhân xoài chua chua ngọt ngọt. Gọi 1 chiếc Mochi cho ngày thật tươi mát. Sản phẩm phải bảo quán mát và dùng ngon nhất trong 2h sau khi nhận hàng.\r\n\r\n', 'sale_price' => 0],
            ['id' => 85, 'name' =>  'Mousse Red Velvet', 'price' => 35000, 'category_id' => 16, 'image' =>  'mousse-red-velvet.jpg', 'description' =>  'Bánh nhiều lớp được phủ lớp kem bên trên bằng Cream cheese.\r\n\r\n', 'sale_price' => 0],
            ['id' => 86, 'name' =>  'Mousse Tiramisu', 'price' => 35000, 'category_id' => 16, 'image' =>  'mousse-tiramisu.jpg', 'description' =>  'Hương vị dễ ghiền được tạo nên bởi chút đắng nhẹ của cà phê lớp kem trứng béo ngọt dịu hấp dẫn\r\n\r\n', 'sale_price' => 0],
            ['id' => 87, 'name' =>  'Mousse Gấu Chocolate', 'price' => 39000, 'category_id' => 16, 'image' =>  'mousse-gau-chocolate.jpg', 'description' =>  'Với vẻ ngoài đáng yêu và hương vị ngọt ngào thơm béo nhất định bạn phải thử ít nhất 1 lần.\r\n\r\n', 'sale_price' => 0],
            ['id' => 88, 'name' =>  'Mít Sấy', 'price' => 20000, 'category_id' => 17, 'image' =>  'mit-say.jpg', 'description' =>  'Mít sấy khô vàng ươm giòn rụm giữ nguyên được vị ngọt lịm của mít tươi.\r\n\r\n', 'sale_price' => 0],
            ['id' => 89, 'name' =>  'Gà Xé Lá Chanh', 'price' => 25000, 'category_id' => 17, 'image' =>  'ga-xe-la-chanh.jpg', 'description' =>  'Thịt gà được xé tơi mang hương vị mặn ngọt cay cay quyện nhau vừa chuẩn thêm chút thơm thơm thơm từ lá chanh sấy khô giòn giòn xua tan ngay cơn buồn miệng.\r\n\r\n', 'sale_price' => 0],
            ['id' => 90, 'name' =>  'Butter Croissant', 'price' => 29000, 'category_id' => 18, 'image' =>  'butter-croissant.jpg', 'description' =>  'Cắn một miếng vỏ bánh ngàn lớp giòn thơm bơ béo rồi mịn tan trong miệng. Cực dính khi nhâm nhi Butter Croissant với cà phê hoặc chấm cùng các món nước có foam trứng của Nhà\r\n\r\n', 'sale_price' => 0],
            ['id' => 91, 'name' =>  'Choco Croffle', 'price' => 39000, 'category_id' => 18, 'image' =>  'choco-croffle.jpg', 'description' =>  'Lạ mắt bắt vị với chiếc bánh Croffle được làm từ cốt bánh Croissant nướng trong khuôn Waffle tổ ong. Trong mềm mịn ngoài giòn thơm thêm topping sô cô la tan chảy ăn là yêu!\r\n\r\n', 'sale_price' => 0],
            ['id' => 92, 'name' =>  'Pate Chaud', 'price' => 39000, 'category_id' => 18, 'image' =>  'pate-chaud.jpg', 'description' =>  'Ngon nức lòng cùng nhân patê và thịt heo cuộn mình trong vỏ bánh ngàn lớp thơm bơ giòn rụm.\r\n\r\n', 'sale_price' => 0],
            ['id' => 93, 'name' =>  'Cà Phê Đen Đá Hộp (14 gói x 16g)', 'price' => 58000, 'category_id' => 19, 'image' => 'ca-phe-den-da-hop.jpg', 'description' => 'Cà Phê Đen Đá hoà tan The Coffee House với 100% hạt cà phê Robusta mang đến hương vị mạnh cực bốc, đậm đắng đầy lôi cuốn, đúng gu người Việt.\r\n\r\n', 'sale_price' => 0],
            ['id' => 94, 'name' =>  'Cà Phê Đen Đá Túi (30 gói x 16g)', 'price' => 110000, 'category_id' => 19, 'image' => 'ca-phe-den-da-tui.jpg', 'description' => 'Cà Phê Đen Đá hoà tan The Coffee House với 100% hạt cà phê Robusta mang đến hương vị mạnh cực bốc, đậm đắng đầy lôi cuốn, đúng gu người Việt.\r\n\r\n', 'sale_price' => 0],
            ['id' => 95, 'name' =>  'Thùng Cà Phê Sữa Espresso', 'price' => 336000, 'category_id' => 19, 'image' =>  'thung-ca-phe-sua-espresso.jpg', 'description' =>  'Được sản xuất theo công nghệ Nhật Cà Phê Sữa Espresso The Coffee House giữ trọn hương vị đậm đà của 100% cà phê Robusta nguyên chất quyện hoà cùng sữa béo thơm lừng. Bật nắp trải nghiệm ngay chất cà phê mạnh mẽ giúp sảng khoái tức thì tuôn trào hứng khởi\r\n\r\n', 'sale_price' => 0],
            ['id' => 96, 'name' =>  'Combo 6 Lon Cà Phê Sữa Espresso', 'price' => 84000, 'category_id' => 19, 'image' =>  'ca-phe-sua-da-pack-6-lon.webp', 'description' =>  'Được sản xuất theo công nghệ Nhật Cà Phê Sữa Espresso The Coffee House giữ trọn hương vị đậm đà của 100% cà phê Robusta nguyên chất quyện hoà cùng sữa béo thơm lừng. Bật nắp trải nghiệm ngay chất cà phê mạnh mẽ giúp sảng khoái tức thì tuôn trào hứng khởi\r\n\r\n', 'sale_price' => 0],
            ['id' => 97, 'name' =>  'Cà Phê Rang Xay Original 1 Túi 1KG', 'price' => 235000, 'category_id' => 19, 'image' =>  'ca-phe-rang-xay-original-1-tui-1kg.webp', 'description' =>  'Cà phê Original 1 của The Coffee House với 100% thành phần cà phê Robusta Đăk Lăk vùng trồng cà phê ngon nhất Việt Nam. Bằng cách áp dụng kỹ thuật rang xay hiện đại Cà phê Original 1 mang đến trải nghiệm tuyệt vời khi uống cà phê tại nhà với hương vị đậm đà truyền thống hợp khẩu vị của giới trẻ sành cà phê.\r\n\r\n', 'sale_price' => 0],
            ['id' => 98, 'name' =>  'Cà Phê Rang Xay Original 1 250g', 'price' => 60000, 'category_id' => 19, 'image' =>  'ca-phe-rang-xay-original-1-250g.jpg', 'description' =>  'Cà phê Original 1 của The Coffee House với thành phần chính cà phê Robusta Đắk Lắk vùng trồng cà phê nổi tiếng nhất Việt Nam. Bằng cách áp dụng kỹ thuật rang xay hiện đại Cà phê Original 1 mang đến trải nghiệm tuyệt vời khi uống cà phê tại nhà với hương vị đậm đà truyền thống hợp khẩu vị của giới trẻ sành cà phê.\r\n\r\n', 'sale_price' => 0],
            ['id' => 99, 'name' =>  'Cà Phê Sữa Đá Hòa Tan (10 gói x 22g)', 'price' => 44000, 'category_id' => 19, 'image' => 'ca-phe-sua-da-hoa-tan.webp', 'description' => 'Thật dễ dàng để bắt đầu ngày mới với tách cà phê sữa đá sóng sánh, thơm ngon như cà phê pha phin. Vị đắng thanh của cà phê hoà quyện với vị ngọt béo của sữa, giúp bạn luôn tỉnh táo và hứng khởi cho ngày làm việc thật hiệu quả.\r\n\r\n', 'sale_price' => 0],
            ['id' => 100, 'name' =>  'Cà Phê Sữa Đá Hòa Tan Túi 25x22G', 'price' => 99000, 'category_id' => 19, 'image' =>  'ca-phe-sua-da-hoa-tan-tui.jpg', 'description' =>  'Thật dễ dàng để bắt đầu ngày mới với tách cà phê sữa đá sóng sánh thơm ngon như cà phê pha phin. Vị đắng thanh của cà phê hoà quyện với vị ngọt béo của sữa giúp bạn luôn tỉnh táo và hứng khởi cho ngày làm việc thật hiệu quả.\r\n\r\n', 'sale_price' => 0],
            ['id' => 101, 'name' =>  'Cà Phê Hoà Tan Đậm Vị Việt (18 gói x 16 gam)', 'price' => 48000, 'category_id' => 19, 'image' => 'ca-phe-hoa-tan-dam-vi-viet.jpg', 'description' => 'Bắt đầu ngày mới với tách cà phê sữa “Đậm vị Việt” mạnh mẽ sẽ giúp bạn luôn tỉnh táo và hứng khởi cho ngày làm việc thật hiệu quả.\r\n\r\n', 'sale_price' => 0],
            ['id' => 102, 'name' =>  'Cà Phê Hòa Tan Đậm Vị Việt Túi 40x16G', 'price' => 99000, 'category_id' => 19, 'image' =>  'ca-phe-hoa-tan-dam-vi-viet-tui.jpg', 'description' =>  'Bắt đầu ngày mới với tách cà phê sữa “Đậm vị Việt” mạnh mẽ sẽ giúp bạn luôn tỉnh táo và hứng khởi cho ngày làm việc thật hiệu quả.\r\n\r\n', 'sale_price' => 0],
            ['id' => 103, 'name' =>  'Cà Phê Sữa Đá Pack 6 Lon', 'price' => 84000, 'category_id' => 19, 'image' =>  'ca-phe-sua-da-pack-6-lon.webp', 'description' =>  'Với thiết kế lon cao trẻ trung hiện đại và tiện lợi Cà phê sữa đá lon thơm ngon đậm vị của The Coffee House sẽ đồng hành cùng nhịp sống sôi nổi của tuổi trẻ và giúp bạn có được một ngày làm việc đầy hứng khởi.\r\n\r\n', 'sale_price' => 0],
            ['id' => 104, 'name' =>  'Thùng 24 Lon Cà Phê Sữa Đá', 'price' => 336000, 'category_id' => 19, 'image' =>  'thung-24-lon-ca-phe-sua-da.jpg', 'description' =>  'Với thiết kế lon cao trẻ trung hiện đại và tiện lợi Cà phê sữa đá lon thơm ngon đậm vị của The Coffee House sẽ đồng hành cùng nhịp sống sôi nổi của tuổi trẻ và giúp bạn có được một ngày làm việc đầy hứng khởi.\r\n\r\n', 'sale_price' => 0],
            ['id' => 105, 'name' =>  'Trà Vị Đào Tearoma 14x14g', 'price' => 32000, 'category_id' => 20, 'image' =>  'tra-vi-dao-tearoma.webp', 'description' =>  'Được chiết xuất từ 100% trà tự nhiên không phẩm màu tổng hợp Trà vị Đào Tearoma mang đến cảm giác thanh mát cực đã. Nhấp một ngụm cảm nhận trọn vị đào chua ngọt thơm ngon bùng nổ. Ngoài ra trà còn bổ sung vitamin C cực kỳ có lợi cho sức khoẻ.\r\n\r\n', 'sale_price' => 0],
            ['id' => 106, 'name' =>  'Trà Sữa Trân Châu Tearoma 250g', 'price' => 38000, 'category_id' => 20, 'image' =>  'tra-sua-tran-chau-tearoma.jpg', 'description' =>  'Chỉ 2 phút có ngay ly Trà sữa trân châu ngon chuẩn vị quán. Thơm vị trà béo vị sữa cùng trân châu thật giòn dai sật sật. Đặc biệt đây còn là thức uống tốt cho sức khoẻ nhờ thành phần 100% chiết xuất trà tự nhiên không chất hoá học.\r\n\r\n', 'sale_price' => 0],
            ['id' => 107, 'name' =>  'Trà Vị Tắc Mật Ong Tearoma 14x14g', 'price' => 32000, 'category_id' => 20, 'image' =>  'tra-vi-tac-mat-ong-tearoma.webp', 'description' =>  'Thổi bùng sảng khoái cùng Trà vị Tắc Mật Ong Tearoma không phẩm màu tổng hợp. Chiết xuất từ 100% trà tự nhiên bổ sung vitamin C tốt cho sức khoẻ. Vị tắc chua chua hoà cùng mật ong ngọt dịu giúp bật vị giác bừng vị mát tức thì.\r\n\r\n', 'sale_price' => 0],
            ['id' => 108, 'name' =>  'Trà Oolong Túi Lọc Tearoma 20x2G', 'price' => 28000, 'category_id' => 20, 'image' =>  'tra-oolong-tui-loc-tearoma.jpg', 'description' =>  'Trà Oolong túi lọc với mùi hương dịu nhẹ hoàn toàn từ tự nhiên vị hậu ngọt và hương thơm tinh tế. Trà túi lọc Tearoma tiện lợi để sử dụng tại văn phòng tại nhà... nhưng vẫn đảm bảo được chất lượng về hương trà tinh tế vị trà đậm đà.\r\n\r\n', 'sale_price' => 0],
            ['id' => 109, 'name' =>  'Trà Lài Túi Lọc Tearoma 20x2G', 'price' => 28000, 'category_id' => 20, 'image' =>  'tra-lai-tui-loc-tearoma.jpg', 'description' =>  'Trà túi lọc Tearoma hương lài thơm tinh tế thanh mát trên nền trà xanh đậm đà khó quên. Trà túi lọc Tearoma tiện lợi để sử dụng tại văn phòng tại nhà.. nhưng vẫn đảm bảo được chất lượng về hương trà tinh tế vị trà đậm đà.\r\n\r\n', 'sale_price' => 0],
            ['id' => 110, 'name' =>  'Trà Sen Túi Lọc Tearoma 20x2G', 'price' => 28000, 'category_id' => 20, 'image' =>  'tra-sen-tui-loc-tearoma.jpg', 'description' =>  'Trà túi lọc Tearoma hương sen tinh tế thanh mát trên nền trà xanh đậm đà khó quên. Trà túi lọc Tearoma tiện lợi để sử dụng tại văn phòng tại nhà đi du lịch... nhưng vẫn đảm bảo được chất lượng về hương trà tinh tế vị trà đậm đà.\r\n\r\n', 'sale_price' => 0],
            ['id' => 111, 'name' =>  'Trà Đào Túi Lọc Tearoma 20x2G', 'price' => 28000, 'category_id' => 20, 'image' =>  'tra-dao-tui-loc-tearoma.jpg', 'description' =>  'Trà túi lọc Tearoma hương đào với hương thơm tinh tế và hoàn toàn tự nhiên cùng nền trà đen đậm vị khó quên. Trà túi lọc Tearoma tiện lợi để sử dụng tại văn phòng tại nhà.. nhưng vẫn đảm bảo được chất lượng về hương trà tinh tế vị trà đậm đà.\r\n\r\n', 'sale_price' => 0]
        ];

        foreach ($products as $key => $value) {
            Product::create($value);
        }
    }
}
